# Generated by Django 3.0.6 on 2020-05-30 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200530_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
