# Generated by Django 3.0.6 on 2020-06-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200601_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='empty', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, default='empty1', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, default='empty2', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, default='empty3', upload_to='uploads/'),
        ),
    ]
