# Generated by Django 3.0.6 on 2020-05-31 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200531_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
