# Generated by Django 3.0.6 on 2020-06-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200601_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image3',
        ),
    ]
