# Generated by Django 3.0.6 on 2020-05-31 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200531_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 18, 22, 0, 272268)),
        ),
    ]
