# Generated by Django 3.0.6 on 2020-06-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200601_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(default='empty2', upload_to='uploads/'),
        ),
    ]
