# Generated by Django 3.0.6 on 2020-06-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200531_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='uploads/'),
        ),
    ]
