# Generated by Django 3.0.6 on 2020-06-01 17:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200601_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, default='empty3', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, default='empty2', upload_to='uploads/'),
        ),
    ]
