# Generated by Django 3.0.6 on 2020-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
